name: Fly
main: net.maplemc.cooper.Main
version: 1.2
api-version: 1.12.2
commands:
   fly:
      description: A simple fly command.
      usage: /fly
   gms:
      description: Sets your gamemode to survival.
      usage: /gms
   gmc:
      description: Sets your gamemode to creative.
      usage: /gmc